on: 
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install ssh keys
      run:
        mkdir /home/runner/.ssh
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd $[{ secrets.WORK_DIR }] && git checkout $[{ secrets.MAIN_BRANCH }] && git pull"
    - name: cleanup
      run: rm -rf ~/.ssh
  
    
