name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: NPM Install
        run: npm install
      - name: Ng Build
        run: npm run build 
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: rsync over SSH
        run: rsync -r ./dist/squart/browser/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:var/www/${{ secrets.HOST }}
